name: 🐛 Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported yet
          required: true
        - label: I have read the documentation and troubleshooting guides
          required: true
        - label: I am using the latest version of gha-pinner
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide your environment details
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - Go version: [e.g., 1.23.0]
        - gha-pinner version: [e.g., v1.0.0]
        - GitHub CLI version: [e.g., 2.40.0]
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command Used
      description: The exact command you ran (sanitize any sensitive information)
      render: bash
      placeholder: gha-pinner local-repository /path/to/repo

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Include any relevant log output, error messages, or stack traces
      render: text
      placeholder: Paste your logs here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...