name: ❓ Question
description: Ask a question about using gha-pinner
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please check the documentation first, then provide details below.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before asking your question
      options:
        - label: I have read the README and documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Installation and Setup
        - Basic Usage
        - Advanced Configuration
        - Integration with CI/CD
        - Troubleshooting
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to achieve
      placeholder: I'm trying to...

  - type: textarea
    id: attempted
    attributes:
      label: What have you tried?
      description: Describe what you've already attempted
      placeholder: I tried...

  - type: textarea
    id: environment
    attributes:
      label: Environment Information (if relevant)
      description: Please provide your environment details if relevant to your question
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 13.0, Windows 11]
        - Go version: [e.g., 1.23.0]
        - gha-pinner version: [e.g., v1.0.0]
        - GitHub CLI version: [e.g., 2.40.0]

  - type: textarea
    id: examples
    attributes:
      label: Code Examples (if applicable)
      description: Include any relevant code, commands, or configuration
      render: yaml
      placeholder: |
        # Your workflow file or command

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Any additional context...